package com.hushunjian.mapper;

import com.hushunjian.domain.CmsUser;
import com.hushunjian.domain.CmsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    long countByExample(CmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    int deleteByExample(CmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    @Delete({
        "delete from cms_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    @Insert({
        "insert into cms_user (id, name, ",
        "created_at)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    int insertSelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    List<CmsUser> selectByExample(CmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    @Select({
        "select",
        "id, name, created_at",
        "from cms_user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.hushunjian.mapper.CmsUserMapper.BaseResultMap")
    CmsUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmsUser record, @Param("example") CmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    int updateByExample(@Param("record") CmsUser record, @Param("example") CmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    int updateByPrimaryKeySelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Feb 06 16:03:16 CST 2018
     */
    @Update({
        "update cms_user",
        "set name = #{name,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CmsUser record);
}