logging:
  config: classpath:logback-spring.xml
mybatis:
  config: classpath:mybatis-config.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apps?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
server:
  port: 9090